include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    use_build_context_synchronously: ignore
    deprecated_member_use: ignore
    unused_element: ignore
    library_private_types_in_public_api: ignore
    unused_import: ignore
    file_names: ignore
    avoid_print: ignore
    non_constant_identifier_names: ignore
