name: bibliapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audio_service: ^0.18.12  # Adicionar esta linha
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  fl_chart: ^0.71.0
  http: ^1.4.0
  shared_preferences: ^2.5.3
  flutter_contacts: ^1.1.9
  permission_handler: ^12.0.0+1
  url_launcher: ^6.2.6
  share_plus: ^11.0.0
  shimmer: ^3.0.0
  provider: ^6.1.1
  flutter_staggered_animations: ^1.1.0
  flutter_html: ^3.0.0-alpha.6
  html: ^0.15.6
  flutter_tts: ^3.6.3
  table_calendar: ^3.0.9
  google_sign_in: ^6.2.1
  supabase_flutter: ^2.3.4
  just_audio: ^0.9.35
  just_audio_background: ^0.0.1-beta.11
  percent_indicator: ^4.2.2
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.0.0
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.25.15

flutter:
  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather-Bold.ttf
          weight: 700
        - asset: assets/fonts/Merriweather-Italic.ttf
        - asset: assets/fonts/Trocchi-Regular.ttf
  assets:
    - assets/logo.png
    - assets/icons/google.png
    - assets/icons/sun_icon.png
    - assets/icons/moon_icon.png
    - assets/biblia_nvi.json
    - assets/images/jo.jpg
    - assets/images/parabolas.png
    - assets/images/proverbios.png
    - assets/images/eclesiastes.png
    - assets/animations/
    - assets/images/
  uses-material-design: true