// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlOYYUb5ClRkd1naHykZxyDwiWVKrrShg',
    appId: '1:959958452938:web:5c6dc639762321ddccc233',
    messagingSenderId: '959958452938',
    projectId: 'appbibliadevocional',
    authDomain: 'appbibliadevocional.firebaseapp.com',
    databaseURL: 'https://appbibliadevocional-default-rtdb.firebaseio.com',
    storageBucket: 'appbibliadevocional.firebasestorage.app',
    measurementId: 'G-DQT4GZ29R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUSBydS9UpH7Ja3kc48tzcNWsGZUZT2V8',
    appId: '1:959958452938:android:309c9cbb930a466fccc233',
    messagingSenderId: '959958452938',
    projectId: 'appbibliadevocional',
    databaseURL: 'https://appbibliadevocional-default-rtdb.firebaseio.com',
    storageBucket: 'appbibliadevocional.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVFFDcUOHqG0nMfb0qowvwHMM6TSgwvyU',
    appId: '1:959958452938:ios:6cbaac73f696f27fccc233',
    messagingSenderId: '959958452938',
    projectId: 'appbibliadevocional',
    databaseURL: 'https://appbibliadevocional-default-rtdb.firebaseio.com',
    storageBucket: 'appbibliadevocional.firebasestorage.app',
    androidClientId: '959958452938-bkdje9c0p6dosbhd1clmpfnn1103d0nl.apps.googleusercontent.com',
    iosClientId: '959958452938-sl2meq6nh0cgjerclm9a0c878lckisvj.apps.googleusercontent.com',
    iosBundleId: 'com.appbibliadevocional.bibliapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVFFDcUOHqG0nMfb0qowvwHMM6TSgwvyU',
    appId: '1:959958452938:ios:6cbaac73f696f27fccc233',
    messagingSenderId: '959958452938',
    projectId: 'appbibliadevocional',
    databaseURL: 'https://appbibliadevocional-default-rtdb.firebaseio.com',
    storageBucket: 'appbibliadevocional.firebasestorage.app',
    androidClientId: '959958452938-bkdje9c0p6dosbhd1clmpfnn1103d0nl.apps.googleusercontent.com',
    iosClientId: '959958452938-sl2meq6nh0cgjerclm9a0c878lckisvj.apps.googleusercontent.com',
    iosBundleId: 'com.appbibliadevocional.bibliapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlOYYUb5ClRkd1naHykZxyDwiWVKrrShg',
    appId: '1:959958452938:web:77257f3bdd3511edccc233',
    messagingSenderId: '959958452938',
    projectId: 'appbibliadevocional',
    authDomain: 'appbibliadevocional.firebaseapp.com',
    databaseURL: 'https://appbibliadevocional-default-rtdb.firebaseio.com',
    storageBucket: 'appbibliadevocional.firebasestorage.app',
    measurementId: 'G-GYFMNEKBNT',
  );
}
