-- First create a temporary table to store existing bookmarks
CREATE TABLE bookmarks_temp AS 
SELECT user_id, verse_id::text, bookmark_type, highlight_color 
FROM bookmarks;

-- Drop the existing table
DROP TABLE bookmarks;

-- Recreate the table with verse_id as integer
CREATE TABLE bookmarks (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    verse_id integer not null,
    bookmark_type text not null check (bookmark_type in ('favorite', 'highlight')),
    highlight_color text,
    created_at timestamptz default now(),
    unique (user_id, verse_id, bookmark_type)
);

-- Copy back the data, converting verse_id to integer where possible
INSERT INTO bookmarks (user_id, verse_id, bookmark_type, highlight_color)
SELECT 
    user_id,
    CASE 
        WHEN verse_id ~ '^\d+$' THEN verse_id::integer 
        ELSE NULL 
    END as verse_id,
    bookmark_type,
    highlight_color
FROM bookmarks_temp
WHERE verse_id ~ '^\d+$'; -- Only copy rows where verse_id is a valid integer

-- Drop the temporary table
DROP TABLE bookmarks_temp;

-- Add indexes for performance
CREATE INDEX bookmarks_user_id_idx ON bookmarks (user_id);
CREATE INDEX bookmarks_verse_id_idx ON bookmarks (verse_id);